language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - pypy
env:
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11.10
  - DJANGO_VERSION=1.11.11
  - DJANGO_VERSION=2.0
# https://docs.djangoproject.com/en/stable/faq/install/#what-python-version-can-i-use-with-django
matrix:
  exclude:
    - env: DJANGO_VERSION=1.9
      python: 3.6
    - env: DJANGO_VERSION=1.10
      python: 3.6
    - env: DJANGO_VERSION=2.0
      python: 3.4
      python: pypy
    - env: DJANGO_VERSION=2.1
      python: 3.4
      python: pypy
addons:
  apt_packages:
    - pandoc
before_install:
    - ./pypi_packager.sh
install:
  - pip install -q django==$DJANGO_VERSION
  - pip install -r requirements/test.txt
  - pip install -e .
script:
  - coverage run --source=autoslugged run_tests.py
after_success:
  - coveralls
